CREATE TABLE IF NOT EXISTS public.json_t
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    json_raw json NOT NULL,
    file_id bigint NOT NULL,
    CONSTRAINT json_t_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.json_t
    OWNER to postgres;	
